version: '3'

services:
  database:
    ports:
      - 54320:5432

  channel_layers:
    ports:
    - 6379:6379

  elva:
    environment:
      - DEBUG=1
   # command: "python manage.py runserver 0.0.0.0:80"
